[package]
name = "axdevice"
version = "0.2.0"
description = "A reusable, OS-agnostic device abstraction layer designed for virtual machines."
homepage = "https://github.com/arceos-hypervisor/axdevice"
repository = "https://github.com/arceos-hypervisor/axdevice"
keywords = ["hypervisor"]
license = "Apache-2.0"
authors = ["aarkegz <aarkegz@gmail.com>"]
documentation = "https://docs.rs/axdevice"
categories = ["virtualization"]
edition = "2024"
readme = "README.md"

[features]

[dependencies]
log = "0.4"
cfg-if = "1.0"
spin = "0.9"

# System independent crates provided by ArceOS.
axerrno = "0.1.0"
memory_addr = "0.4"

axvmconfig = { version = "0.1", default-features = false }
axaddrspace = "0.1"
axdevice_base = "0.1"
range-alloc-arceos = "0.1.4-pre.1"

[target.'cfg(target_arch = "aarch64")'.dependencies]
arm_vgic = { version = "0.1", features = ["vgicv3"] }

[target.'cfg(target_arch = "riscv64")'.dependencies]
riscv_vplic = { git = "https://github.com/arceos-hypervisor/riscv_vplic.git", rev = "8bc5213" }

[dev-dependencies]
axdevice_base = "0.1"
axaddrspace = "0.1"
memory_addr = "0.4"
axerrno = "0.1"
axvmconfig = "0.1"

[patch.crates-io]
axvmconfig = { git = "https://github.com/arceos-hypervisor/axvmconfig.git", branch = "next" }